### ISSUE TITLE
Which ros version does the code apply to?

### ISSUE THREAD

**Issue by ljy-zju** [kehanXue/dv_ros#1]
My computer configuration is ubuntu18.04, ros melodic,  g++ 7.5.0 and gcc 7.5.0
When I compile this code on my computer, it first prompts me:
CMake Error in dv_ros/CMakeLists.txt:
   The compiler feature "cxx_std_20" is not known to CXX compiler

   "GNU"

   version 7.5.0.

Can you help with this problem?
Thank you so much~~

**Comment by kehanXue** [comment]
C++20 features are available since GCC 8. You need to upgrade your GNU version.
